---
apiVersion: v1
kind: Namespace
metadata:
  name: controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chainguard-controller
  namespace: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chainguard-controller-role
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["security.chainguard.dev"]
  resources: ["imagepolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["security.chainguard.dev"]
  resources: ["imagepolicies/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["security.chainguard.dev"]
  resources: ["imagepolicies/finalizers"]
  verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chainguard-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chainguard-controller-role
subjects:
- kind: ServiceAccount
  name: chainguard-controller
  namespace: controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainguard-controller
  namespace: controller
  labels:
    app: chainguard-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chainguard-controller
  template:
    metadata:
      labels:
        app: chainguard-controller
        admission.datadoghq.com/enabled: "false" 
    spec:
      serviceAccountName: chainguard-controller
      containers:
      - name: manager
        image: jonlimpw/secure-controller@sha256:00ac43fde4134be02f38413e63472f229aae3fa849b7e1af21fc0f27d4ab9434
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: chainguard-controller-metrics
  namespace: controller
  labels:
    app: chainguard-controller
spec:
  selector:
    app: chainguard-controller
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
