apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: default
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: jonlimpw/demo-app:latest  # This will be flagged as non-compliant (using tag instead of digest)
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    monitored: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliant-app
  namespace: demo
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: jonlimpw/demo-app@sha256:placeholder-digest-will-be-updated  # This will be compliant when using actual digest
        ports:
        - containerPort: 8080
