apiVersion: security.chainguard.dev/v1
kind: ImagePolicy
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: imagepolicy-sample
spec:
  # TODO(user): Add fields here
