apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-slsa-attestations
  annotations:
    description: "Require SLSA attestations for container images"
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: check-slsa-attestation
    match:
      any:
      - resources:
          kinds:
          - Pod
          - Deployment
          - StatefulSet
          - DaemonSet
    validate:
      message: "Container images must have SLSA attestations"
      foreach:
      - list: "request.object.spec.containers"
        deny:
          conditions:
            any:
            - key: "{{ element.image }}"
              operator: AnyNotIn
              value: 
              - "jonlimpw/cg-demo@sha256:*"  # Only allow digest-based images
              - "jonlimpw/secure-controller@sha256:*"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slsa-validation-script
  namespace: kube-system
data:
  validate-slsa.sh: |
    #!/bin/bash
    # SLSA validation script for admission controller
    
    IMAGE=$1
    
    # Extract repository and digest
    REPO=$(echo $IMAGE | cut -d'@' -f1)
    DIGEST=$(echo $IMAGE | cut -d'@' -f2)
    
    # Check if image has SLSA attestation
    # This would integrate with your attestation storage/registry
    
    echo "Validating SLSA attestation for $IMAGE"
    
    # Example validation logic:
    # 1. Check if attestation exists
    # 2. Verify attestation signature
    # 3. Validate builder identity
    # 4. Check source repository
    
    # For demo purposes, allow images with digests
    if [[ $IMAGE == *"@sha256:"* ]]; then
        echo "✅ Image uses digest - SLSA compliance assumed"
        exit 0
    else
        echo "❌ Image uses tag - SLSA attestation required"
        exit 1
    fi
---
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: requireslsaattestation
spec:
  crd:
    spec:
      names:
        kind: RequireSLSAAttestation
      validation:
        type: object
        properties:
          allowedRepositories:
            type: array
            items:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package requireslsaattestation
        
        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          not has_slsa_attestation(container.image)
          msg := sprintf("Container image %v must have SLSA attestation", [container.image])
        }
        
        has_slsa_attestation(image) {
          # Check if image uses digest (indicates attestation)
          contains(image, "@sha256:")
        }
        
        has_slsa_attestation(image) {
          # Allow specific repositories with attestations
          startswith(image, input.parameters.allowedRepositories[_])
        }
---
apiVersion: templates.gatekeeper.sh/v1beta1
kind: RequireSLSAAttestation
metadata:
  name: slsa-attestation-required
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedRepositories:
      - "jonlimpw/cg-demo@"
      - "jonlimpw/secure-controller@"
