---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.chainguard.dev
  resources:
  - imagepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.chainguard.dev
  resources:
  - imagepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - security.chainguard.dev
  resources:
  - imagepolicies/status
  verbs:
  - get
  - patch
  - update
