#!/bin/bash

# Check GitHub Actions attestations using GitHub CLI
# This demonstrates how to verify attestations generated by GitHub Actions

set -e

echo "🔍 GitHub Actions Attestation Verification"
echo "=========================================="
echo ""

# Check if GitHub CLI is installed
if ! command -v gh &> /dev/null; then
    echo "📥 Installing GitHub CLI..."
    
    if [[ "$OSTYPE" == "darwin"* ]]; then
        brew install gh
    else
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh
    fi
    
    echo "✅ GitHub CLI installed successfully"
    echo ""
fi

# Repository and image details
REPO="jon94/chainguard-controller-poc"
IMAGE_NAME="jonlimpw/cg-demo"

echo "🎯 Repository: $REPO"
echo "🎯 Image: $IMAGE_NAME"
echo ""

echo "📋 GitHub Actions Attestation Commands:"
echo "======================================="
echo ""

echo "1️⃣ List Attestations for Repository:"
echo "------------------------------------"
echo "gh attestation list --repo $REPO"
echo ""

echo "2️⃣ Verify Attestation for Specific Image:"
echo "-----------------------------------------"
echo "gh attestation verify oci://$IMAGE_NAME:latest --repo $REPO"
echo ""

echo "3️⃣ Download Attestation Bundle:"
echo "-------------------------------"
echo "gh attestation download --repo $REPO --predicate-type=https://slsa.dev/provenance/v0.2"
echo ""

echo "4️⃣ Verify with Custom Predicate Type:"
echo "-------------------------------------"
echo "gh attestation verify oci://$IMAGE_NAME:latest \\"
echo "  --repo $REPO \\"
echo "  --predicate-type=https://slsa.dev/provenance/v0.2"
echo ""

echo "🔍 Manual Verification Steps:"
echo "============================="
echo ""

echo "Step 1: Authenticate with GitHub"
echo "gh auth login"
echo ""

echo "Step 2: Check if attestations exist"
echo "gh attestation list --repo $REPO"
echo ""

echo "Step 3: Verify specific image"
echo "gh attestation verify oci://$IMAGE_NAME@\$(docker inspect $IMAGE_NAME:latest --format='{{index .RepoDigests 0}}' | cut -d'@' -f2) --repo $REPO"
echo ""

echo "📊 Attestation Validation Workflow:"
echo "==================================="
echo ""
echo "1. 🔍 Discovery: Find available attestations"
echo "2. 📥 Download: Retrieve attestation bundles"
echo "3. ✅ Verify: Validate cryptographic signatures"
echo "4. 🔎 Inspect: Examine attestation content"
echo "5. 🛡️  Enforce: Apply policy decisions"
echo ""

echo "🎯 Enterprise Integration:"
echo "========================="
echo ""
echo "• Integrate with CI/CD pipelines for automated verification"
echo "• Use in Kubernetes admission controllers"
echo "• Combine with policy engines (OPA, Kyverno)"
echo "• Monitor compliance dashboards"
echo ""

echo "⚠️  Note: GitHub attestations require the repository to have"
echo "   attestation generation enabled in GitHub Actions workflows."
